name: CI-CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Autenticando usuário no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Construindo a imagem e enviando para o Docker Hub
        uses: docker/build-push-action@v3.1.0
        with:
          file: ./aula4-pipeline/src/Dockerfile
          context: ./aula4-pipeline/src
          push: true
          tags: |
            eduardocortez3/kube-news:latest
            eduardocortez3/kube-news:${{github.run_number}}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3

      - name: Autenticando no Cluster Kubernetes
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      
      - name: Aplicando o manifesto no Cluster Kubernetes
        uses: Azure/k8s-deploy@v4.3
        with:
          images: eduardocortez3/kube-news:${{github.run_number}}
          manifests:
            aula4-pipeline/k8s/deployment.yaml