name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          file: ./aula4-pipeline/src/Dockerfile
          context: ./aula4-pipeline/src
          push: true
          tags: |
            eduardocortez3/kube-news:latest
            eduardocortez3/kube-news:${{github.run_number}}
